[package]
name = "fortify-http"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
fortify-core = { path = "../fortify-core" }
fortify-gate = { path = "../fortify-gate" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
hyper = { version = "0.14", features = ["server", "client", "http1", "tcp"] }
hyper-tls = "0.5"
http = "0.2"
bytes = "1.5"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
urlencoding = "2.1"
reqwest = { version = "0.13", features = ["blocking", "json"] }
uuid = { version = "1.19.0", features = ["v4", "fast-rng"] }
lazy_static = "1.4"
