# Fortify Resource Limits

# Max open files
*    soft nofile 65536
*    hard nofile 65536

# Max processes
*    soft nproc  4096
*    hard nproc  4096

# Core dumps disabled
*    soft core   0
*    hard core   0

# Max locked memory
*    soft memlock 64
*    hard memlock 64
